# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: JurgenRathlev.InnoUnpacker
PackageVersion: 2.0.5.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: InnoUnpacker_is1
ReleaseDate: 2025-08-25
AppsAndFeaturesEntries:
- ProductCode: InnoUnpacker_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://www.rathlev-home.de/tools/download/innounpacker-setup.exe
  InstallerSha256: FFAF6406F4C1EFBA50A565C6C2E0C79349AD82A6C5992E3D492C943C8737D192
ManifestType: installer
ManifestVersion: 1.10.0
